import { StoreCategoryIcon } from "@models";

export const CATEGORIES_ICONS: StoreCategoryIcon[] = [
  "docs",
  "android",
  "desktop",
  "attributes",
  "browse",
  "bucket",
  "calendarStart",
  "clock",
  "command",
  "conversations",
  "creditCard",
  "pin",
  "feed",
  "form",
  "gift",
  "heart",
  "newFolder",
  "private",
  "sparkle",
  "star",
  "subscribe",
  "sync",
  "tag",
  "user",
  "windows",
  "copy",
  "settings",
  "palmtree",
];